import { ToastContainer } from "react-toastify";
import type { Metadata } from "next";
import { Oswald } from "next/font/google";

import "./globals.css";

import Navbar from "@/component/shared/Navbar";
import Footer from "@/component/shared/Footer";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <div>{children}</div>
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}